Q.what is broadcasting in numpy explain with example what are different rules in broadcasting

In [1]:
#Broadcasting
import numpy as np

Rule 1

In arithmetics operations both array must have same shape.

In [2]:
#both rows and columns are equal
a=np.array([[1,2],[3,4]])
b=np.array([[1,1],[2,2]])
print(a)
print('Shape of a : ',a.shape)#shape inbuilt method to find dimensions of matrix
print(b)
print('Shape of b : ',b.shape)
c=np.add(a,b)
print(c)
print('Shape of a : ',a.shape)

[[1 2]
 [3 4]]
Shape of a :  (2, 2)
[[1 1]
 [2 2]]
Shape of b :  (2, 2)
[[2 3]
 [5 6]]
Shape of a :  (2, 2)


Rule 2

If shapes of both arrays are different then atleast row or column of one array should be equal to 1.

In [3]:
#here column of 2nd array is equal to 1
a=np.array([[1,2],[3,4],[1,1]])
b=np.array([1,2])
print(a)
print('Shape of a : ',a.shape)
print(b)
print('Shape of b : ',b.shape)
c=np.add(a,b)
print(c)
print('Shape of a : ',a.shape)

[[1 2]
 [3 4]
 [1 1]]
Shape of a :  (3, 2)
[1 2]
Shape of b :  (2,)
[[2 4]
 [4 6]
 [2 3]]
Shape of a :  (3, 2)
