Q.what is zeros ones ,full functions and what is vstack,column_stack,hstack in numpy

-zeros() and ones() are the NumPy library functions to create two different arrays.

zeros() function is used to create an array based on the particular shape and type.

All array elements are initialized to 0,which is created by the zeros() function.



In [3]:
import numpy as np
a=np.zeros([2,2],dtype=int)
print(a)

[[0 0]
 [0 0]]


-ones() function works like the zeros() function,All array elements are initialized to 1.

In [4]:
import numpy as np
a=np.ones([2,2],dtype=int)
print(a)

[[1 1]
 [1 1]]


-full(shape, fill_value, dtype = None, order = ‘C’) : 

Return a new array with the same shape and type as a given array filled with a fill_value

In [11]:
import numpy as np
a=np.full([3,3],5,dtype=int)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


-vstack() is a function in Python which is used to vertically stack sequences of input arrays 

in order to make a single array.

With vstack() function, you can append data vertically.

In [8]:
import numpy as np
i=np.array([1,2,3])
j=np.array([4,5,6])
a=np.vstack((i,j))
print(a)

[[1 2 3]
 [4 5 6]]


-column_stack() function is used to stack 1-D arrays as columns into a 2-D array.

It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array.

In [10]:
import numpy as np
i=np.array([1,2,3])
j=np.array([4,5,6])
a=np.column_stack((i,j))
print(a)

[[1 4]
 [2 5]
 [3 6]]


-hstack() is a function that is used to horizontally stack sequences of input arrays in order to make a single array.

With hstack() function in Python,you can append data horizontally.

It is a very convenient function in NumPy.

In [9]:
import numpy as np
i=np.array([1,2,3])
j=np.array([4,5,6])
a=np.hstack((i,j))
print(a)

[1 2 3 4 5 6]
