#Convert a 1D array to a 2D array with 2 rows
np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
#Create 1D array
import numpy as np
A=np.arange(10)#arange() inbuilt function to create array
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#convert 1D array to 2D array with 2 rows
A=A.reshape(2,5)#reshape() inbuilt function to change shape of array
print('2D array with 2 rows \n',A)

2D array with 2 rows 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
