Q.what is boolean indexing explain with example?

Ans.

Boolean indexing is defined as a very important feature of numpy,
which is frequently used in pandas.

Its main task is to use the actual values of the data in the DataFrame.

Boolean value : True or False


In [4]:
import numpy as np
a=np.array([[0,20,3],[-4,5,-6],[7,0,98]])
print(a)
print(a>5) #boolean indexing of array a

[[ 0 20  3]
 [-4  5 -6]
 [ 7  0 98]]
[[False  True False]
 [False False False]
 [ True False  True]]


In [7]:
#if we want to give boolean indexing according to our condition
boolean=np.where(a==0,False,True)#if value equals to zero then False ow True
print(boolean)

[[False  True  True]
 [ True  True  True]
 [ True False  True]]
